version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "npm dependencies"	  
# Disable version updates for pip dependencies
    open-pull-requests-limit: 0
    
