name: Scan with Insider
on:
  pull_request:
  push:
jobs:
  scan-insider:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Insider
        uses: insidersec/insider-action@v0
        with:
          technology: javascript
